server:
  http:
    port: 8080
    read_timeout: 60s
    write_timeout: 60s

datasource:
  type: mysql
  user: root
  password: 123456
  host: 127.0.0.1:3306
  name: album

redis:
  addr: 127.0.0.1:6379

jwt:
  secret: 23347$040412
